### ISSUE TITLE
What is this for

### ISSUE THREAD

**Issue by Immortalin** [lolibrary/lolibrary#24]
Add description to README?

**Comment by Immortalin** [comment]
i.e. is it for ecommerce, patterns, or just grand archive of clothing?

**Comment by ChunCVL** [comment]
Dear Immortalin,

The intention/vision of this project is to create a website which can be used to archive Lolita fashion clothing, If I am understanding the code correctly they are now busy with trying optimize the search method.

Last but not least I see also some try development in API calls. I think the intention for that is so that people can add/edit information of fashion items of the Lolita fashion.

The code they are using are mainly PHP (Framework Laravel), Bootstrap for some fronted work and some GO for potential API calls.

~Chun

**Comment by Immortalin** [comment]
Thanks!
